Merge speaker talk data file
satRdays/hugo-satrdays-theme pull request #39
Opened 2020-10-19 20:16 UTC by RMHogervorst

Fix #7 and probably #28 too.

2020-10-20 06:34 UTC, RMHogervorst commented
Modify the modal to also include bio of speaker and uses the profile picture:
![Screenshot 2020-10-20 at 08 31 16](https://user-images.githubusercontent.com/9538040/96548746-b8dc8000-12ae-11eb-94b2-291f2176e29b.png)
Talks part still works, tweetthis partial includes name of speaker (easy because it is in the same file)
![Screenshot 2020-10-20 at 08 30 35](https://user-images.githubusercontent.com/9538040/96548750-baa64380-12ae-11eb-886c-5445b9bc0417.png)

![Screenshot 2020-10-20 at 08 30 52](https://user-images.githubusercontent.com/9538040/96548753-bbd77080-12ae-11eb-9aa8-414a3818c774.png)

2020-10-20 06:39 UTC, RMHogervorst commented
Summarizing:

This PR:
* merges the speaker and talks files into one schedule/TalkXX.toml 
* adds that file to the theme
* modifies the relevant partials
* rebased against develop

2020-10-24 14:01 UTC, DaveParr commented
This looks really great, and thanks for the rebase, you'd read my mind. I've decided (partly thanks to all your work this month) that we need to have a develop branch as the PR target. 

I've changed the target of this PR to that manually, I think because of your rebase that means everything is as intended.

I'm very happy to merge this in right now, and it does close #7 . It also almsot completely closes #28 with one exception:

The twitter user is not tagged by their handle (e.g. @sometwitterthing ) in the intent. I think this should be doable with a 'small' modification:

Currently the `social` section of what is now the `data/schedule/talkx.toml` like it does [in this file from Columbus2020](https://github.com/satRdays/Columbus2020/blob/master/data/speakers/alec-wong.toml). The key/awakward part is that it expects a full string such as `"https://twitter.com/Awong234"`. Would it be possible to extend the `tweetthis.html` partial with some form of string parsing, so it extracts only the handle from the url?

The double awkward bit would be the logic of putting in only the speakers 'listed' name if that twitter handle value was not present.

If you're interested in having a crack at that it would be awesome. As it is right now though I'd gratefully merge this in as is if you'd rather.

2020-10-24 14:04 UTC, DaveParr requested changes
Sorry, tiny change needed here. Git conflict seemed to go a bit wonky.

2020-10-24 14:04 UTC, DaveParr commented on layouts/index.html
> +>>>>>>> 8ae97e6... include hackathon section
Something might have gone a little awry here with a git conflict. Effectively this change just isn't a change :)

2020-10-24 17:11 UTC, RMHogervorst commented
Let me check tomorrow

2020-10-25 08:31 UTC, RMHogervorst commented
I think that string parsing thing should to be a separate issue.
Let me check if I can fix it up today.

2020-10-25 13:08 UTC, DaveParr approved these changes

2020-10-29 17:28 UTC, merged

2020-10-29 17:28 UTC, DaveParr commented
I'm going ahead to merge this. We can tackle that twitter handle string parsing problem in another branch.

Thanks a tonne for this :)